setw -g mode-keys vi
set -g status-keys vi
set -g default-terminal "screen-256color"
set -g history-limit 500000

# 建议自己配置 hostname
#   sudo hostname YOUR_NEW_HOSTNAME
#   sudo hostnamectl set-hostname YOUR_NEW_HOSTNAME